### ISSUE TITLE
[feature request] - support for multiple node selectors

### ISSUE THREAD

**Issue by vikas027** [che-incubator/kubernetes-image-puller#94]
It would be good to have support for multiple node selectors with a map like this

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-image-puller
data:
  NODES:
    - IMAGES: "alpine=alpine:3.12; alpine13=alpine:3.13; alpine-minimal=vikas027/alpine:minimal;"
      DAEMONSET_NAME: "kubernetes-image-puller"
      CACHING_INTERVAL_HOURS: "1"
      NAMESPACE: "k8s-image-puller""
      NODE_SELECTOR:
        app: abcd1
      IMAGE_PULL_SECRETS: "some secret"
    - IMAGES: "alpine3=alpine:3.0;"
      DAEMONSET_NAME: "kubernetes-image-puller"
      CACHING_INTERVAL_HOURS: "1"
      NAMESPACE: "k8s-image-puller""
      NODE_SELECTOR:
        app: abcd2
```
